name: Daily Data Process

on:
  schedule:
    - cron: "0 9 * * *" # 台北下午5點下班時間
  #push:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      timeout-minutes: 15
      run: |
        npm i
        npm run process
    - name: Commit files
      timeout-minutes: 15
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "更新健保署資料" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

